# Generated by Django 5.0.2 on 2024-03-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='classes',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(blank=True, choices=[('1', 'Fighter'), ('2', 'Wizard'), ('3', 'Rogue'), ('4', 'Cleric'), ('5', 'Druid'), ('6', 'Paladin'), ('7', 'Barbarian'), ('8', 'Ranger'), ('9', 'Bard'), ('10', 'Monk'), ('11', 'Sorcerer'), ('12', 'Warlock')], max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=16),
        ),
    ]
